
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 700
SCREEN_TITLE = "The Penguins' Revenge"
FRAME_LENGTH = 0.05

LEFT_VIEWPORT_MARGIN = 250
RIGHT_VIEWPORT_MARGIN = 250
BOTTOM_VIEWPORT_MARGIN = 50
TOP_VIEWPORT_MARGIN = 100

TILE_SCALING = 1

SPRITE_SCALING = 0.5
SPRITE_NATIVE_SIZE = 128
SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * SPRITE_SCALING)
BULLET_SPEED = 8

#Constants for working with player penguin health bar/text
HEALTHBAR_WIDTH = 40
HEALTHBAR_HEIGHT = 5
HEALTHBAR_OFFSET_Y = 40

HEALTH_NUMBER_OFFSET_X = -10
HEALTH_NUMBER_OFFSET_Y = 33

TILE_SCALING = 1
